#!/bin/bash

# initial setup for my aws clients after `aws configure`

set -e
set -x

source ./utils.sh
aws_prerequisites

echo "Using account: ${AWS_CLIENT_PEM}"

aws ec2 create-key-pair --key-name $AWS_CLIENT_PEM --query 'KeyMaterial' --output text > ~/.ssh/${AWS_CLIENT_PEM}.pem
chmod 400 ~/.ssh/${AWS_CLIENT_PEM}.pem

aws ec2 describe-key-pairs --key-name $AWS_CLIENT_PEM


aws ec2 create-security-group --group-name webserver --description "open port 80/443"
aws ec2 create-security-group --group-name dbserver --description "open port 3306"
aws ec2 create-security-group --group-name administrable --description "open everything to admin ips"

aws ec2 authorize-security-group-ingress --group-name dbserver --protocol tcp --port 3306 --source-group webserver

aws ec2 authorize-security-group-ingress --group-name webserver --protocol tcp --port 80 --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-name webserver --protocol tcp --port 443 --cidr 0.0.0.0/0
