#!/bin/bash

# AWS
# credentials, here or ~/.aws/credentials
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
export AWS_DEFAULT_PROFILE="default"
export AWS_DEFAULT_REGION="eu-central-1"
export AWS_DEFAULT_OUTPUT="json"

# custom
export AWS_CLIENT_PEM="aws"
export AWS_AVAILABILITY_ZONE="eu-central-1a"
